# Generated by Django 2.2.7 on 2019-11-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20191113_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name_plural': 'galleries'},
        ),
    ]
