# Generated by Django 2.2.7 on 2019-11-12 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\([0-9]{3}\\)[0-9]{3}-[0-9]{4}$')])),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='coaches/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
