# Generated by Django 2.2.7 on 2019-11-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('p', 'Practice'), ('n', 'No practice'), ('t', 'Tournament')], default='p', max_length=1)),
                ('cover_image', models.FileField(upload_to='tournaments/')),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
