# Generated by Django 2.2.7 on 2019-11-13 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(help_text='Enter phone in following format (111)111-11-11', max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\([0-9]{3}\\)[0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(help_text='Enter phone in following format (111)111-11-11', max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\([0-9]{3}\\)[0-9]{3}-[0-9]{4}$')]),
        ),
    ]
