# Generated by Django 2.2.7 on 2019-11-13 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20191113_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(help_text='Enter phone in the following format (111)111-11-11', max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\([0-9]{3}\\)[0-9]{3}(-[0-9]{2}){2}|$')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(help_text='Enter phone in the following format (111)111-1111', max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\([0-9]{3}\\)[0-9]{3}(-[0-9]{2}){2}|$')]),
        ),
    ]
