# Generated by Django 2.2.7 on 2019-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20191113_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
