# Generated by Django 2.2.7 on 2019-11-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_coach_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
